### ISSUE TITLE
sample usage?

### ISSUE THREAD

**Issue by johndpope** [Tarnadas/smm-protobuf#1]
I run 

npm install -g

all seems fine.
what's the next command to load smm course file course_data.cdt or spit out a javascript file to read / parse course ?

some attempts I made to manually execute the scripts in package.json

```shell
npm install pbjs@0.0.5 -g

/usr/local/bin/pbjs -> /usr/local/lib/node_modules/pbjs/cli.js
+ pbjs@0.0.5
updated 1 package in 1.065s
(tensorflow) ➜  smm-protobuf git:(master) ✗ pbjs -t json ./proto/SMMCourse.proto
/usr/local/lib/node_modules/pbjs/node_modules/protocol-buffers-schema/parse.js:240
      throw new Error('Expected protobuf syntax version but found ' + version)
      ^

Error: Expected protobuf syntax version but found 'proto3'
    at onsyntaxversion (/usr/local/lib/node_modules/pbjs/node_modules/protocol-buffers-schema/parse.js:240:13)
    at Function.parse (/usr/local/lib/node_modules/pbjs/node_modules/protocol-buffers-schema/parse.js:569:25)
    at Object.exports.parseSchema (/usr/local/lib/node_modules/pbjs/index.js:6:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/pbjs/cli.js:21:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)

```

I have nvm 8.0.0

**Comment by johndpope** [comment]
import crc32 from 'buffer-crc32'
import protobuf from 'protobufjs'
import * as proto from 'proto/bundle.json'
import fileType from 'file-type'
import readChunk from 'read-chunk'
import Zip from 'node-7z'
import tmp from 'tmp'
import rimraf from 'rimraf'

import fs from 'fs'
import path from 'path'
import zlib from 'zlib'

import { loadCourse } from '.'


const sound = Buffer.concat([Buffer.from('76246AAE', 'hex'), Buffer.alloc(0xD804)], 0xD808)

const root = protobuf.Root.fromJSON(proto)
const smmCourse = root.lookupType('SMMCourse')
